[package]
edition = "2021"
name = "library"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casbin = {version = "2.0.9", default-features = false, features = ["logging"]}
chrono = {version = "0.4"}
db = {path = "../db"}
jsonwebtoken = {version = "8"}
jwt = "0.16.0"
once_cell = "1.10.0"
poem = {version = "1.3.35"}
poem-casbin-auth = {git = "https://github.com/casbin-rs/poem-casbin", branch = "main"}
scru128 = "2"
sea-orm = "0.9.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1"}
thiserror = {version = "1"}
tokio = {version = "1"}
tracing = "0.1.34"
tracing-subscriber = "0.3"
warp = {version = "0.3"}
