[package]
edition = "2021"
name = "library"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.10.0"
poem = {version = "1.2"}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1"}
tokio = {version = "1"}
