[http_server]
address = "127.0.0.1"
name = "cloud"
port = 8022

[static_server]
dir = "static"
index = "index.html"
upload_dir = "uploads"
upload_url = ""

[log]
dir = "logs"
filename = "info"
log_level = "debug"

[db]
db_name = "poem_cloud"
db_type = "mysql"
host = "127.0.0.1"
password = "root123123"
port = 3306
username = "root"
