use poem::http::StatusCode;
use poem::http::header::AUTHORIZATION;
use poem::{Endpoint, Middleware, Request, Result, Error};
use library;
pub struct JwtMiddleware;

impl<E: Endpoint> Middleware<E> for JwtMiddleware {
    type Output = JwtMiddlewareImpl<E>;

    fn transform(&self, ep: E) -> Self::Output {
        JwtMiddlewareImpl { ep }
    }
}

/// The new endpoint type generated by the TokenMiddleware.
pub struct JwtMiddlewareImpl<E> {
    ep: E,
}

#[poem::async_trait]
impl<E: Endpoint> Endpoint for JwtMiddlewareImpl<E> {
    type Output = E::Output;

    async fn call(&self, mut req: Request) -> Result<Self::Output> {
        if let Some(value) = req
            .headers()
            .get(AUTHORIZATION)
            .and_then(|value| value.to_str().ok())
            .filter(|value| value.starts_with("Bearer "))
            .map(|value| &value[7..])
        {
            // Decode JWT token
            let decode_res = library::jwt::claims::decode_jwt(value);
            let claims = match decode_res {
                Ok(c) => c,
                Err(err) => return Err(Error::from_string(err.to_string(), StatusCode::INTERNAL_SERVER_ERROR)),
            };
            req.extensions_mut().insert(claims);
        }

        // call the next endpoint.
        self.ep.call(req).await
    }
}