//! SeaORM Entity. Generated by sea-orm-codegen 0.9.0

pub use super::account::Entity as Account;
pub use super::menu::Entity as Menu;
pub use super::sys_config::Entity as SysConfig;
pub use super::user::Entity as User;
pub use super::vm_types::Entity as VmTypes;
pub use super::vms::Entity as Vms;
